using BackendAPI.Data;
using BackendAPI.Models;
using Npgsql;

namespace BackendAPI.Services
{
    /// <summary>
    /// Handles CRUD operations for inventory categories.
    /// Categories define thresholds used for low-stock alerting.
    /// </summary>
    public class CategoryService
    {
        private readonly DbHelper _db;

        public CategoryService(DbHelper db)
        {
            _db = db;
        }

        /// <summary>
        /// Retrieves categories with optional search, sorting, and threshold filtering.
        /// Search is case-insensitive against category_name using ILIKE.
        /// Sorting supports: category_id, category_name, threshold.
        /// </summary>
        public async Task<List<Category>> GetAllAsync(string search, string sortBy, string sortOrder, int? thresholdMin)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();

            // Build dynamic WHERE clause based on provided filters
            var conditions = new List<string>();
            var cmd = new NpgsqlCommand();

            if (!string.IsNullOrWhiteSpace(search))
            {
                conditions.Add("category_name ILIKE @search");
                cmd.Parameters.AddWithValue("search", $"%{search}%");
            }

            if (thresholdMin.HasValue)
            {
                conditions.Add("threshold >= @thresholdMin");
                cmd.Parameters.AddWithValue("thresholdMin", thresholdMin.Value);
            }

            var where = conditions.Count > 0 ? "WHERE " + string.Join(" AND ", conditions) : "";

            // Whitelist sort columns to prevent SQL injection via user input
            var sortColumn = sortBy switch
            {
                "category_name" => "category_name",
                "threshold" => "threshold",
                _ => "category_id"
            };
            var order = sortOrder.ToLower() == "desc" ? "DESC" : "ASC";

            cmd.CommandText = $"SELECT category_id, category_name, threshold FROM category {where} ORDER BY {sortColumn} {order}";
            cmd.Connection = conn;

            using var reader = await cmd.ExecuteReaderAsync();
            var categories = new List<Category>();
            while (await reader.ReadAsync())
            {
                categories.Add(new Category
                {
                    CategoryId = reader.GetInt32(0),
                    CategoryName = reader.GetString(1),
                    Threshold = reader.GetInt32(2)
                });
            }
            return categories;
        }

        /// <summary>
        /// Inserts a new category. The category_id is auto-generated by PostgreSQL SERIAL.
        /// </summary>
        public async Task AddAsync(Category category)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();

            using var cmd = new NpgsqlCommand(@"
                INSERT INTO category (category_name, threshold)
                VALUES (@name, @threshold)", conn);
            cmd.Parameters.AddWithValue("name", category.CategoryName);
            cmd.Parameters.AddWithValue("threshold", category.Threshold);

            await cmd.ExecuteNonQueryAsync();
        }

        /// <summary>
        /// Updates name and threshold for an existing category.
        /// Returns false if category_id doesn't exist.
        /// </summary>
        public async Task<bool> UpdateAsync(int id, Category category)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();

            using var cmd = new NpgsqlCommand(@"
                UPDATE category SET category_name = @name, threshold = @threshold
                WHERE category_id = @id", conn);
            cmd.Parameters.AddWithValue("name", category.CategoryName);
            cmd.Parameters.AddWithValue("threshold", category.Threshold);
            cmd.Parameters.AddWithValue("id", id);

            return await cmd.ExecuteNonQueryAsync() > 0;
        }

        /// <summary>
        /// Deletes a category by ID. Returns false if not found.
        /// Note: Consider checking for linked items before deleting in production.
        /// </summary>
        public async Task<bool> DeleteAsync(int id)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();

            using var cmd = new NpgsqlCommand("DELETE FROM category WHERE category_id = @id", conn);
            cmd.Parameters.AddWithValue("id", id);

            return await cmd.ExecuteNonQueryAsync() > 0;
        }
    }
}
