using BackendAPI.Data;
using BackendAPI.Models;
using Npgsql;

namespace BackendAPI.Services
{
    /// <summary>
    /// Manages purchase detail records linked to consumable items.
    /// Handles adding new purchases and batch-deleting purchases
    /// with stock rollback validation.
    /// </summary>
    public class PurchaseService
    {
        private readonly DbHelper _db;

        public PurchaseService(DbHelper db)
        {
            _db = db;
        }

        /// <summary>
        /// Returns all purchase records for a given item.
        /// </summary>
        public async Task<List<PurchaseDetail>> GetByItemIdAsync(int itemId)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();

            using var cmd = new NpgsqlCommand(@"
                SELECT order_id, item_id, quantity, price, purchase_date
                FROM purchase_details WHERE item_id = @id
                ORDER BY order_id", conn);
            cmd.Parameters.AddWithValue("id", itemId);

            using var reader = await cmd.ExecuteReaderAsync();
            var list = new List<PurchaseDetail>();
            while (await reader.ReadAsync())
            {
                list.Add(new PurchaseDetail
                {
                    OrderId = reader.GetInt32(0),
                    ItemId = reader.GetInt32(1),
                    Quantity = reader.GetInt32(2),
                    Price = reader.GetDecimal(3),
                    PurchaseDate = reader.GetString(4)
                });
            }
            return list;
        }

        /// <summary>
        /// Adds a new purchase record for an item.
        /// The order_id is auto-generated by PostgreSQL SERIAL.
        /// </summary>
        public async Task AddAsync(int itemId, PurchaseDetail purchase)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();
            using var transaction = await conn.BeginTransactionAsync();

            using var cmd = new NpgsqlCommand(@"
                INSERT INTO purchase_details (item_id, quantity, price, purchase_date)
                VALUES (@itemId, @qty, @price, @date)", conn);

            cmd.Parameters.AddWithValue("itemId", itemId);
            cmd.Parameters.AddWithValue("qty", purchase.Quantity);
            cmd.Parameters.AddWithValue("price", purchase.Price);
            cmd.Parameters.AddWithValue("date", purchase.PurchaseDate);

            await cmd.ExecuteNonQueryAsync();

            using var updateCmd = new NpgsqlCommand(@"
                UPDATE consumable_items SET quantity = quantity + @qty
                WHERE item_id = @itemId", conn);
            
            updateCmd.Parameters.AddWithValue("qty", purchase.Quantity);
            updateCmd.Parameters.AddWithValue("itemId", itemId);
            
            await updateCmd.ExecuteNonQueryAsync();
            await transaction.CommitAsync();
        }

        /// <summary>
        /// Batch-deletes purchase records and rolls back inventory stock.
        /// 
        /// Business logic:
        /// 1. Look up each order_id to find its quantity
        /// 2. Sum total quantity across all orders being deleted
        /// 3. Validate current stock >= total rollback quantity (can't go negative)
        /// 4. Subtract stock for each order and delete the purchase record
        /// 
        /// Returns (success, errorMessage). errorMessage is null on success.
        /// </summary>
        public async Task<(bool success, string? error)> DeletePurchasesAsync(DeletePurchasesRequest request)
        {
            using var conn = _db.CreateConnection();
            await conn.OpenAsync();

            int totalToSubtract = 0;
            var orderQuantities = new Dictionary<int, int>();

            // Step 1: Validate each order exists and accumulate quantities
            foreach (var orderId in request.OrderIds)
            {
                using var findCmd = new NpgsqlCommand(@"
                    SELECT quantity FROM purchase_details
                    WHERE order_id = @orderId AND item_id = @itemId", conn);
                findCmd.Parameters.AddWithValue("orderId", orderId);
                findCmd.Parameters.AddWithValue("itemId", request.ItemId);

                var qty = await findCmd.ExecuteScalarAsync();
                if (qty == null) continue; // Skip non-existent orders silently

                var quantity = (int)qty;
                totalToSubtract += quantity;
                orderQuantities[orderId] = quantity;
            }

            // Step 2: Check if current stock can absorb the rollback
            using var stockCmd = new NpgsqlCommand(
                "SELECT quantity FROM consumable_items WHERE item_id = @id", conn);
            stockCmd.Parameters.AddWithValue("id", request.ItemId);

            var currentStock = await stockCmd.ExecuteScalarAsync();
            if (currentStock == null)
                return (false, "Item not found in consumable_items.");

            if (totalToSubtract > (int)currentStock)
                return (false, $"Cannot delete purchases. Required rollback ({totalToSubtract}) exceeds current stock ({(int)currentStock}).");

            // Step 3: Perform the deletions and stock adjustments
            foreach (var kvp in orderQuantities)
            {
                // Deduct stock
                using var deduct = new NpgsqlCommand(@"
                    UPDATE consumable_items SET quantity = quantity - @qty
                    WHERE item_id = @itemId", conn);
                deduct.Parameters.AddWithValue("qty", kvp.Value);
                deduct.Parameters.AddWithValue("itemId", request.ItemId);
                await deduct.ExecuteNonQueryAsync();

                // Delete purchase record
                using var del = new NpgsqlCommand(@"
                    DELETE FROM purchase_details
                    WHERE order_id = @orderId AND item_id = @itemId", conn);
                del.Parameters.AddWithValue("orderId", kvp.Key);
                del.Parameters.AddWithValue("itemId", request.ItemId);
                await del.ExecuteNonQueryAsync();
            }

            return (true, null);
        }
    }
}
